name: flutter_sqlite # Puedes poner aquí el nombre de tu proyecto
description: "Una aplicación de Flutter con SQLite."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  # sqflite_common_ffi: ^2.3.3 # Descomenta esta línea si vas a probar en escritorio o web

dev_dependencies:
  flutter_test:
    sdk: flutter
  # ESTA LÍNEA ES LA CLAVE PARA SOLUCIONAR TU PROBLEMA
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true